# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [1]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [19]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [20]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2L, 4L)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [6]:
l1=[1,2]
l2=[4,5]
np.array([l1,l2])



array([[1, 2],
       [4, 5]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [11]:
mat1=np.matrix('9 8 7 ; 6 5 4 ; 3 2 1')

In [12]:
print (mat1)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [17]:
mat2=mat1.T
print(mat2)

[[9 6 3]
 [8 5 2]
 [7 4 1]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [18]:
mat3=mat2+1
print (mat3)

[[10  7  4]
 [ 9  6  3]
 [ 8  5  2]]


Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [21]:
nd6 = np.matrix(' 1 4 9 121 144 169 ;16 25 36 196 225 256 ; 49 64 81 289 324 361')
print(nd6)

[[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]


In [22]:
nd6.mean()

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [23]:
a1=np.matrix('1 2 ; 3 4')
a2=np.matrix('5 6 ; 7 8')
np.dot(a1,a2)

matrix([[19, 22],
        [43, 50]])